public class com_CreateAccContWrapper {
    @AuraEnabled public String Accountid;
    @AuraEnabled public String ContactId;
    @AuraEnabled public Case myCase;
    @AuraEnabled public String AccName;
    @AuraEnabled public String AccSource;
    @AuraEnabled public String AccWebForm;
    @AuraEnabled public String AccCountry;
    @AuraEnabled public String ConFirst;
    @AuraEnabled public String ConSecond;
    @AuraEnabled public String ConEmail;
    @AuraEnabled public String ConPhone;
    @AuraEnabled public Boolean isPopup;
}